enableVersioning: true
handle: sessions
name: Sessions
propagationMethod: all
siteSettings:
  0c55c71d-f02b-49e0-bb11-7d8691a2e8b5:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'sessions/{slug}'
type: channel
